

## External sources

---------- [1] ---------- 
2024-01-14T23:05:34Z-06 

Solve issue with launch file error on xacro output when py launch is nested in xml launch file. 

https://answers.ros.org/question/417369/caught-exception-in-launch-see-debug-for-traceback-unable-to-parse-the-value-of-parameter-robot_description-as-yaml/

